baseURL = "http://gafgaf.infoaed.ee/"
languageCode = "et-ee"
defaultContentLanguage = "et"
title = "üêï √úks Tartu krants"
theme = "massively"
enableRobotsTXT = true
canonifyURLs = true

[Author]
  name = "M√§rt P√µder"

[params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

# Below parameters can be set to override default post settings
[params.posts]
     foldername = "posts"
     pagesize = "52"
     featuredpost = "false"

[languages]
[languages.et]
  languageName = "Eesti keeles"
[languages.ru]
  languageName = "–ü–æ-—Ä—É—Å—Å–∫–∏"
[languages.en]
  languageName = "In English"
