baseURL = "http://gafgaf.infoaed.ee/"
languageCode = "et-ee"
defaultContentLanguage = "et"
title = "ğŸ• Ãœks Tartu krants"
theme = "massively"

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

# Below parameters can be set to override default post settings
[params.posts]
     foldername = "posts"
     pagesize = "42"
     featuredpost = "false"


[languages]
[languages.et]
  languageName = "Eesti keeles"
[languages.ru]
  languageName = "ĞŸĞ¾-Ñ€ÑƒÑÑĞºĞ¸"
[languages.en]
  languageName = "In English"
